import pandas as pd

# Load your CSV file
file_path = 'expenseVsGDP.csv'  # Update with your actual file path
df = pd.read_csv(file_path)

# Create the extended dictionary for country code to continent mapping
extended_country_code_to_continent = {
    'AFG': 'Asia',
    'ALA': 'Europe',
    'ALB': 'Europe',
    'DZA': 'Africa',
    'ASM': 'Oceania',
    'AND': 'Europe',
    'AGO': 'Africa',
    'AIA': 'North America',
    'ATA': 'Antarctica',
    'ATG': 'North America',
    'ARG': 'South America',
    'ARM': 'Asia',
    'ABW': 'North America',
    'AUS': 'Oceania',
    'AUT': 'Europe',
    'AZE': 'Asia',
    'BHS': 'North America',
    'BHR': 'Asia',
    'BGD': 'Asia',
    'BRB': 'North America',
    'BLR': 'Europe',
    'BEL': 'Europe',
    'BLZ': 'North America',
    'BEN': 'Africa',
    'BMU': 'North America',
    'BTN': 'Asia',
    'BOL': 'South America',
    'BIH': 'Europe',
    'BWA': 'Africa',
    'BVT': 'Antarctica',
    'BRA': 'South America',
    'VGB': 'North America',
    'IOT': 'Asia',
    'BRN': 'Asia',
    'BGR': 'Europe',
    'BFA': 'Africa',
    'BDI': 'Africa',
    'KHM': 'Asia',
    'CMR': 'Africa',
    'CAN': 'North America',
    'CPV': 'Africa',
    'CYM': 'North America',
    'CAF': 'Africa',
    'TCD': 'Africa',
    'CHL': 'South America',
    'CHN': 'Asia',
    'HKG': 'Asia',
    'MAC': 'Asia',
    'CXR': 'Asia',
    'CCK': 'Asia',
    'COL': 'South America',
    'COM': 'Africa',
    'COG': 'Africa',
    'COD': 'Africa',
    'COK': 'Oceania',
    'CRI': 'North America',
    'CIV': 'Africa',
    'HRV': 'Europe',
    'CUB': 'North America',
    'CYP': 'Asia',
    'CZE': 'Europe',
    'DNK': 'Europe',
    'DJI': 'Africa',
    'DMA': 'North America',
    'DOM': 'North America',
    'ECU': 'South America',
    'EGY': 'Africa',
    'SLV': 'North America',
    'GNQ': 'Africa',
    'ERI': 'Africa',
    'EST': 'Europe',
    'ETH': 'Africa',
    'FLK': 'South America',
    'FRO': 'Europe',
    'FJI': 'Oceania',
    'FIN': 'Europe',
    'FRA': 'Europe',
    'GUF': 'South America',
    'PYF': 'Oceania',
    'ATF': 'Antarctica',
    'GAB': 'Africa',
    'GMB': 'Africa',
    'GEO': 'Asia',
    'DEU': 'Europe',
    'GHA': 'Africa',
    'GIB': 'Europe',
    'GRC': 'Europe',
    'GRL': 'North America',
    'GRD': 'North America',
    'GLP': 'North America',
    'GUM': 'Oceania',
    'GTM': 'North America',
    'GGY': 'Europe',
    'GIN': 'Africa',
    'GNB': 'Africa',
    'GUY': 'South America',
    'HTI': 'North America',
    'HMD': 'Antarctica',
    'VAT': 'Europe',
    'HND': 'North America',
    'HUN': 'Europe',
    'ISL': 'Europe',
    'IND': 'Asia',
    'IDN': 'Asia',
    'IRN': 'Asia',
    'IRQ': 'Asia',
    'IRL': 'Europe',
    'IMN': 'Europe',
    'ISR': 'Asia',
    'ITA': 'Europe',
    'JAM': 'North America',
    'JPN': 'Asia',
    'JEY': 'Europe',
    'JOR': 'Asia',
    'KAZ': 'Asia',
    'KEN': 'Africa',
    'KIR': 'Oceania',
    'PRK': 'Asia',
    'KOR': 'Asia',
    'KWT': 'Asia',
    'KGZ': 'Asia',
    'LAO': 'Asia',
    'LVA': 'Europe',
    'LBN': 'Asia',
    'LSO': 'Africa',
    'LBR': 'Africa',
    'LBY': 'Africa',
    'LIE': 'Europe',
    'LTU': 'Europe',
    'LUX': 'Europe',
    'MKD': 'Europe',
    'MDG': 'Africa',
    'MWI': 'Africa',
    'MYS': 'Asia',
    'MDV': 'Asia',
    'MLI': 'Africa',
    'MLT': 'Europe',
    'MHL': 'Oceania',
    'MTQ': 'North America',
    'MRT': 'Africa',
    'MUS': 'Africa',
    'MYT': 'Africa',
    'MEX': 'North America',
    'FSM': 'Oceania',
    'MDA': 'Europe',
    'MCO': 'Europe',
    'MNG': 'Asia',
    'MNE': 'Europe',
    'MSR': 'North America',
    'MAR': 'Africa',
    'MOZ': 'Africa',
    'MMR': 'Asia',
    'NAM': 'Africa',
    'NRU': 'Oceania',
    'NPL': 'Asia',
    'NLD': 'Europe',
    'ANT': 'North America',
    'NCL': 'Oceania',
    'NZL': 'Oceania',
    'NIC': 'North America',
    'NER': 'Africa',
    'NGA': 'Africa',
    'NIU': 'Oceania',
    'NFK': 'Oceania',
    'MNP': 'Oceania',
    'NOR': 'Europe',
    'OMN': 'Asia',
    'PAK': 'Asia',
    'PLW': 'Oceania',
    'PSE': 'Asia',
    'PAN': 'North America',
    'PNG': 'Oceania',
    'PRY': 'South America',
    'PER': 'South America',
    'PHL': 'Asia',
    'PCN': 'Oceania',
    'POL': 'Europe',
    'PRT': 'Europe',
    'PRI': 'North America',
    'QAT': 'Asia',
    'REU': 'Africa',
    'ROU': 'Europe',
    'RUS': 'Europe',
    'RWA': 'Africa',
    'BLM': 'North America',
    'SHN': 'Africa',
    'KNA': 'North America',
    'LCA': 'North America',
    'MAF': 'North America',
    'SPM': 'North America',
    'VCT': 'North America',
    'WSM': 'Oceania',
    'SMR': 'Europe',
    'STP': 'Africa',
    'SAU': 'Asia',
    'SEN': 'Africa',
    'SRB': 'Europe',
    'SYC': 'Africa',
    'SLE': 'Africa',
    'SGP': 'Asia',
    'SVK': 'Europe',
    'SVN': 'Europe',
    'SLB': 'Oceania',
    'SOM': 'Africa',
    'ZAF': 'Africa',
    'SGS': 'Antarctica',
    'SSD': 'Africa',
    'ESP': 'Europe',
    'LKA': 'Asia',
    'SDN': 'Africa',
    'SUR': 'South America',
    'SJM': 'Europe',
    'SWZ': 'Africa',
    'SWE': 'Europe',
    'CHE': 'Europe',
    'SYR': 'Asia',
    'TWN': 'Asia',
    'TJK': 'Asia',
    'TZA': 'Africa',
    'THA': 'Asia',
    'TLS': 'Asia',
    'TGO': 'Africa',
    'TKL': 'Oceania',
    'TON': 'Oceania',
    'TTO': 'North America',
    'TUN': 'Africa',
    'TUR': 'Asia',
    'TKM': 'Asia',
    'TCA': 'North America',
    'TUV': 'Oceania',
    'UGA': 'Africa',
    'UKR': 'Europe',
    'ARE': 'Asia',
    'GBR': 'Europe',
    'USA': 'North America',
    'UMI': 'Oceania',
    'URY': 'South America',
    'UZB': 'Asia',
    'VUT': 'Oceania',
    'VEN': 'South America',
    'VNM': 'Asia',
    'VIR': 'North America',
    'WLF': 'Oceania',
    'ESH': 'Africa',
    'YEM': 'Asia',
    'ZMB': 'Africa',
    'ZWE': 'Africa'
}

# Apply the mapping to the dataframe to fill missing continents
df['Continent'] = df['Code'].map(extended_country_code_to_continent).fillna(df['Continent'])

# Save the updated dataframe back to a CSV file
output_file_path = 'expenseVsGDP.csv'  # Update with your desired file path
df.to_csv(output_file_path, index=False)

print("The continent field has been successfully filled and the updated file has been saved.")